employeedb:
  image: wlmpoc/centos_mysql
  container_name: employeedb
  hostname: employeedb
  entrypoint: [ "/usr/bin/nohup"  ]
  command: "/root/startdb.sh restart && tailf /dev/null" 
 
djweb:
  image: wlmpoc/debianjessie_djwebapp
  hostname: DjangoAppContainer
  container_name: DjangoAppContainer
  command: python manage.py runserver 0.0.0.0:8082
  volumes:
   - .:/home/wlmdevops/DjWebappJessie/backupdir/
  ports:
    - "40000:8082"
  links:
    - employeedb
