employeedb:
  image: wlmpoc/centos_mysql
  container_name: employeedb
  hostname: employeedb
djweb:
  image: wlmpoc/debianjessie_djwebapp
  hostname: DjangoAppContainer
  working_dir: /home/wlmdevops/DjWebappJessie/
  command: python manage.py runserver 0.0.0.0:8080
  volumes:
   - .:/home/wlmpoc/DjWebappJessie/
  ports:
    - "8080:8080"
  links:
    - employeedb
